### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by kovmir** [lcomrade/lenpaste#11]
Steps taken:
```bash
git clone https://github.com/lcomrade/lenpaste.git # PLEASE FIX DEAD URL IN README.md
cd ./lenpaste/
git checkout v1.3
sudo docker build -t localhost/lenpaste:latest ./
```

`docker build ...` fails with the following output:
```
=> [build 2/8] WORKDIR /build                                                                     17.9s
 => ERROR [build 3/8] RUN apk add --no-cache make=4.3-r1 git=2.38.3-r1 gcc=12.2.1_git20220924-r4 m  2.7s
------
 > [build 3/8] RUN apk add --no-cache make=4.3-r1 git=2.38.3-r1 gcc=12.2.1_git20220924-r4 musl-dev=1.2.3-r4:
#13 0.713 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
#13 1.258 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
#13 1.648 ERROR: unable to select packages:
#13 1.704   git-2.38.5-r0:
#13 1.704     breaks: world[git=2.38.3-r1]
#13 1.704   musl-dev-1.2.3-r5:
#13 1.704     breaks: world[musl-dev=1.2.3-r4]
------
process "/bin/sh -c apk add --no-cache make=4.3-r1 git=2.38.3-r1 gcc=12.2.1_git20220924-r4 musl-dev=1.2.3-r4" did not complete successfully: exit code: 2```

You should add a GitHub Action to build your `Dockerfile` on each tag or something...

**Comment by lcomrade** [comment]
Fixed in Lenpaste version 1.3.1. The problem occurred because there were some Golang libraries on git.lcomrade.su. Also Dockerfile tried to download old versions of Alpine packages that were removed from official repositories some time ago.

The Docker image can now be built following [these instructions](https://github.com/lcomrade/lenpaste/tree/192388ad2b8c42750db458ef7cbe3bb3edea4da0#build-docker-image-recommended) in the README.

If you are using an older version of Docker, you may experience problems with the build. If something doesn't work, you should try installing the Docker version from the [official Docker site](https://docs.docker.com/engine/install/). I am building in Fedora 39 using Docker `24.0.7, build afdd53b`.
